### ISSUE TITLE
Have a logo

### ISSUE THREAD

**Issue by williamdes** [air-balloon/data#1]

**Comment by williamdes** [comment]
Hi @AdrianoCahete
Would you be interested in contributing to my new project or maybe your friend that did work on the phpMyAdmin logo ?
Here is an history entry: https://github.com/air-balloon/data/blob/main/HISTORY.md#the-project-history
I will be posting logo proposals here and intend to close this topic quickly if I remain the only contributor to this subject for more than a week.

**Comment by williamdes** [comment]
You can see 21a95706ce09c4c04c33a90d40f1b6bdaeecd968 for the actual logos

**Comment by AdrianoCahete** [comment]
I'll see the data in the next days!

**Comment by williamdes** [comment]
> I'll see the data in the next days!

Thank you so much

**Comment by AdrianoCahete** [comment]
Just an update: I come to an idea and may move to create the logo in Figma this week, I think.

**Comment by williamdes** [comment]
> Just an update: I come to an idea and may move to create the logo in Figma this week, I think.

Oh cool, thank you for the update !

**Comment by AdrianoCahete** [comment]
Sorry about the delay. My friend is on a big project and cannot help with this project, so I made the main idea and make a few alternatives.

<p align="center">
<img width="319" alt="airballoon_1" src="https://user-images.githubusercontent.com/37474/102140567-2e437780-3e3e-11eb-8a05-1ef4ce8aee32.png">
</p>

---

<p align="center">
<img width="416" alt="airballoon_2" src="https://user-images.githubusercontent.com/37474/102140577-33082b80-3e3e-11eb-99ee-cf6b6f62bcbe.png">

</p>

---

<p align="center">
<img width="368" alt="airballoon_3" src="https://user-images.githubusercontent.com/37474/102140590-37ccdf80-3e3e-11eb-8dff-296c35737521.png">

</p>

---

<p align="center">
<img width="280" alt="airballoon_4" src="https://user-images.githubusercontent.com/37474/102140603-3c919380-3e3e-11eb-9b1d-8d403e3a6654.png">

</p>

---

<p align="center">
<img width="280" alt="airballoon_5" src="https://user-images.githubusercontent.com/37474/102140612-41564780-3e3e-11eb-9d1a-ce8a9c84ddde.png">

</p>

I like the **first** logo, but it's your choice. :)

**Comment by williamdes** [comment]
Hi! 
Thank you for working on this 👏, they are cool but I would choose the first one or the one with the O used as a basket
What do you think @Guileas?

**Comment by Guileas** [comment]
@williamdes For me the last one or the first one

**Comment by williamdes** [comment]
I would want to add more stripes to the balloon ?

By the way @AdrianoCahete `balloon` has 2 l ;)

**Comment by AdrianoCahete** [comment]
> I would want to add more stripes to the balloon?

It's possible, but if you need to use in a small placement, these lines will be just a big blur
![airballoon_1-small](https://user-images.githubusercontent.com/37474/102140884-b4f85480-3e3e-11eb-8443-58e0415b162c.png)

This example is a 70px height logo. For comparison, Github logo on header has 32px and Twitter has 23px.


> By the way @AdrianoCahete balloon has 2 l ;)

Fixed, my bad :P

**Comment by williamdes** [comment]
Thank you, I agree to let is as it is :)
Can you open a pull-request here to add the source files ?
What license are they under ?

**Comment by AdrianoCahete** [comment]
> Can you open a pull-request here to add the source files?

Yep! I'll do this ASAP. Is the first one then, right?

> What license are they under?

It's a good question. I was planning to leave it to you to decide, since it's more the logo for your project, even if it's my creation, but keeping the proper attribution. 
Searching for a "Choose a License", I found that the "[CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/?ref=chooser-v1)" looks like that: has attribution, anyone can use even if it's commercial, cannot be modified (since it's a logo, so to keep the logo in a safe place, cannot be modified) and no derivates (because the same idea: it's a logo, to keep the brand-safe cannot be modified).

It's ok for you?

For the attribution, you can use: `Adriano Cahete <https://adrianocahete.dev/>`

**Comment by williamdes** [comment]
> Yep! I'll do this ASAP. Is the first one then, right?

Yup, the first real logo. I did publish the actual "logo" as https://github.com/air-balloon/data/commit/21a95706ce09c4c04c33a90d40f1b6bdaeecd968 unsorted at the root of this repository ^^

> It's ok for you?


Yes, It seems okay.
Does it mean I need to make a new logo next time I want to change it ?


> For the attribution, you can use: Adriano Cahete <https://adrianocahete.dev/>

How does it work, where I am required to put the attribution ?
And what to do in case of a commercial product ?

**Comment by AdrianoCahete** [comment]
> Yup, the first real logo. I did publish the actual "logo" as 21a9570 unsorted at the root of this repository ^^

I made the real svg exported here, I'll create a PR soon (just fixing some DNS on another pet project first)

> Does it mean I need to make a new logo next time I want to change it?

By the base license, I think it is, but since I'm the author I think I can opt-out of this making you/the project team the authors too (since it's your idea and your project, I'm just a tool here)?
In the case of a commercial product, the license permits:

> **You are free to:**
>    Share — copy and redistribute the material in any medium or format for any purpose, even commercially. 
>
> **Under the following terms:**
>    Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
>    NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.

**Comment by williamdes** [comment]
I would agree just if you can post a GPG signed text that says that we can distribute the logo but with attribution of the initial logo?

"you may not distribute the modified material." this is a little hard, let me know what you think

Good arguments can convince me ^^

**Comment by AdrianoCahete** [comment]
I can, but I don't know how to do this? hahaha
Neither the "output of sha512 and sign the output with your GPG key" that you said on PR. :(

**Comment by williamdes** [comment]
Here is an example, do what you think is the best ;)
```
echo -e 'text\ntext' | gpg --clear-sign --armor -u williamdes@wdes.fr
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

text
text
-----BEGIN PGP SIGNATURE-----

iQJHBAEBCgAxFiEExNkf3872tKPGU/14kKDvG4JRqIkFAl/ZBx8THHdpbGxpYW1k
ZXNAd2Rlcy5mcgAKCRCQoO8bglGoiUN1D/9skYBxRSl2e0A74Z8Jhk3OSHqTziMN
g+hfvyGwJog9hEkuCBu78xYB8xLEq1RrcVvRPZDfjcTW3bNZqyuL9cdgqvUZqPXp
fhZcdJXdJE+k8rhquoUF55MVPJRwh7JLoSrby9umNpIDZx4rtuqwq5RqkxEEYVhE
y7AWtIiNYOhUL0Fy6TddITQlWPfJgl2bU7L8Wb/PPmVqJ0sXee5egf6ternANWeg
qOKhthYKjRsI1VkiZ+CMnPZBS7c7ukfBdSWi1W05wJrKx6lYro9yiRKrVxYRVfif
Vf+EGLVxUYPBiMhp4m1o2dV1klzoc4J8+rS8tobu1IDgG/RuRz4EnDLRyMU4dOed
yfvZmCPGrhwQy7AWNwidN3pLLUGic3xj2qO5mPcZhViNjtaT4fcFHA9DO54dlyRh
p9ieoD1nJHE84GyRQBhk9sy48WpeAMj2BG5ysnMc9JU7flUgNwjAVRwjVMvFgzmt
Czv1FKbN/sCsfFpfcQzw/SVt0osY+wTyFUJ8jXkMVCPOUFBy/rxTjCCDtlLg95Pi
cPoat35dxCcYRIxSBUL3yRoV63nAXpEjRCURdNd2OW1OX3sLAC3WsSpW/sSVyDJL
+rJl24Iio8zyOUf75nd897WjbwxYSFsSzQVj9UVBdnkEfC+0FwsBq2FlB2h4jXi/
Z+huJvMZWnhvnw==
=RCxu
-----END PGP SIGNATURE-----
```

**Comment by AdrianoCahete** [comment]
See if you find that this text is ok.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

The air-balloon logo is a work by Adriano Cahete <https://adrianocahete.dev/> to air-balloon project <https://github.com/air-balloon> and it's licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License <https://creativecommons.org/licenses/by-nd/4.0/>. The project team share the authoring in this logo, therefore they have the same rights.
-----BEGIN PGP SIGNATURE-----

iQJJBAEBCgAzFiEEoTWQEwTnE/46OddzMnDXOoo0PWQFAl/ZP1cVHG1lQGFkcmlh
bm9jYWhldGUuZGV2AAoJEDJw1zqKND1k6d4P/3nJYHPRxAHqwDsQ2+2D50SrcgBg
nztxrVEpOtaLUGbg0vs1vfBkKlvsvkgpf6kKSnUZ3r/hvlyG5gwlgAqg2YxgaoTR
0ZocR0gqVggrhmZL2a4Dr6KIhUHCvq7vvu4t5odyFm2cvz+8fk46kcjP+x6iKnyS
gLLXoRuX85AEKIi6TI3qJUVpCT35w7CqrdWlTkzDCoQNf5hul1GdTk7oFVi/Vrcl
XgxFghKI2Br+JLri4qYH0wfOvmxfO9AzYfjjHNptUZgVm/ZdDrWGissvGiBStgSf
RDb9BCNU/Phry4e5A/egy9pT5JDgnVCmJes8puxtgm5BDfur4NZHHNk9cVheF9cM
+FPMlVOtUXfYUCNFrk6cHp33qcUVaR0c3cry++WMTUZirlgaBSgUIz8nRgduV+19
OIdfmqwo4+oRlPJfTvzWNktiKIn2+jGVdt46GO3HpPR17F+nJ1Q+h2xVpmzCUSry
H2Nr6p0BG4cjR2GuDWTbUcNjhn55X9G264AgTC0F99FhK1ghWTz5TEV6CqfQkQvi
zXw074DcYPVt0gAUO7IVspVYbd8giu9/mckBaFpswKPO9cz4QcL6RNRmrVySixr9
CuMzv1PNXOVadpXLrwDQ0SBYqw3V7OWrZ/4JzMgebjO25zm0MDZ+6sKKwkjGRBO7
pKu/jMjiDRXrBaEC
=A6tq
-----END PGP SIGNATURE-----
```

**Comment by williamdes** [comment]
Hi !
This is perfect, that said I could not verify it because your public key seems not to be on a keyserver.
Could you follow https://gist.github.com/williamdes/0d49288fecf83bf491cc1e6366ae7c30#upload-the-key to upload it please ?

**Comment by AdrianoCahete** [comment]
Sent (I think) :)

**Comment by williamdes** [comment]
> Sent (I think) :)

Awesome !

```
gpg: Signature made Tue Dec 15 23:57:27 2020 CET
gpg:                using RSA key A135901304E713FE3A39D7733270D73A8A343D64
gpg:                issuer "me@adrianocahete.dev"
gpg: Good signature from "Adriano Cahete <me@adrianocahete.dev>" [unknown]
```

**Comment by AdrianoCahete** [comment]
This fixes the PR problem or I still need to follow your steps there?

**Comment by williamdes** [comment]
> This fixes the PR problem or I still need to follow your steps there?

Well as you want, you can just sign your files on the PR (see my comment) and we will be ready. But you can decide to skip this step
